version: "3.9"  # Versión del esquema de Compose, compatible con Docker Compose v2+

services:

  ddns:
    image: ddns-updater:alpine
    container_name: ddns-updater
    hostname: ddns-updater
    volumes:
      - ./params:/root/params
      - ./logs:/root/logs
    restart: unless-stopped

  vpn-server:
    image: vpn-server:alpine
    container_name: vpn-server
    hostname: vpn-server
    volumes:
      - ./config:/root/config
      - ./params:/root/params
      - ./logs:/root/logs
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  tunnel:
    image: tunnel-server:alpine
    container_name: tunnel-server
    hostname: tunnel-server
    volumes:
      - ./params:/root/params
      - ./logs:/root/logs
    networks:
      - proxy-net
    restart: unless-stopped

  proxy:
    image: proxy-server:alpine
    container_name: proxy-server
    hostname: proxy-server
    volumes:
      - ./params:/root/params
      - ./logs:/root/logs
      - ./config:/root/config
    networks:
      - proxy-net
      - prod-net
      - uat-net
    restart: unless-stopped

  prod-app:
    image: fake-prod-server:alpine
    container_name: prod-server
    hostname: prod-server
    networks:
      - prod-net
    restart: unless-stopped

  uat-app:
    image: fake-uat-server:alpine
    container_name: uat-server
    hostname: uat-server
    networks:
      - uat-net
    restart: unless-stopped

networks:
  proxy-net:
    driver: bridge
  prod-net:
    driver: bridge
  uat-net:
    driver: bridge

