#!/bin/bash

root_path="$1"
[ -z "$root_path" ] && root_path="$HOME"
message="$2"

if [ ! -z "$message" ]; then
    caller=${BASH_SOURCE[1]}

    log_max_file_size=$(jq -r '.proxy.log.max_file_size' "$PARAMS_FILE")
    [ -z "$log_max_file_size" ] && log_max_file_size=10000  # Default to 10000 lines if not set
    log_max_quantity_files=$(jq -r '.proxy.log.max_quantity_files' "$PARAMS_FILE")
    [ -z "$log_max_quantity_files" ] && log_max_quantity_files=5  # Default to 5 files if not set

    log_path="$root_path/logs"

    [ -d "$log_path" ] || mkdir -p "$log_path"

    [ -z "$log_file" ] && log_file="$log_path/$( date '+%Y-%m-%d-%H-%M-%S' )-$( cat /etc/hostname ).log"

    if [ -f "$log_file" ]; then
        log_size=$(wc -l < "$log_file")

        if [ "$log_size" -ge "$log_max_file_size" ]; then
            log_file="$log_path/$( date '+%Y-%m-%d-%H-%M-%S' )-$( cat /etc/hostname ).log"
        fi
    else
        touch "$log_file"
        chown "1000:1000" "$log_file"
        chown "1000:1000" "$log_path"
    fi

    echo "[$( date '+%Y-%m-%d %H:%M:%S' )] $caller: $message" >> "$log_file"

    files=($(ls -1 "$log_path"/*.log 2>/dev/null | sort))

    total_files=${#files[@]}

    if [ "$total_files" -gt "$log_max_quantity_files" ]; then
        files_to_delete=$((total_files - log_max_quantity_files))
        for ((i = 0; i < files_to_delete; i++)); do
            rm -f "${files[$i]}"
        done
    fi
fi