#!/bin/bash

set -e

[ -z "$1" ] && root_path="$HOME" || root_path="$1"

# Verifica si el archivo de parametros existe y tiene contenido si no existe termina la ejecucion
if [ ! -s "$PARAMS_FILE" ]; then
    log "$root_path" " Params file not found, please add to \"$PARAMS_FILE\"." "$0"
    exit 1
fi
